# Generated by Django 3.1.5 on 2021-04-02 23:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('achName', models.CharField(max_length=300)),
                ('achLogo', models.ImageField(default='achLogos/default.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeOfBirth', models.CharField(blank=True, max_length=400)),
                ('parentsAgeAtBirth', models.CharField(blank=True, max_length=400)),
                ('descriptionOfBirth', models.CharField(blank=True, max_length=400)),
                ('aboutEAT', models.CharField(blank=True, max_length=400)),
                ('premorbidState', models.CharField(blank=True, max_length=400)),
                ('peculiaritiesInDevelopment', models.CharField(blank=True, max_length=400)),
                ('lifeConditions', models.CharField(blank=True, max_length=400)),
                ('jobDescription', models.CharField(blank=True, max_length=400)),
                ('badHabits', models.CharField(blank=True, max_length=400)),
                ('lifeStyle', models.CharField(blank=True, max_length=400)),
                ('dietDescription', models.CharField(blank=True, max_length=400)),
                ('pastIllnesses', models.CharField(blank=True, max_length=400)),
                ('surgicalInterventions', models.CharField(blank=True, max_length=400)),
                ('hereditaryDiseases', models.CharField(blank=True, max_length=400)),
                ('pastInfections', models.CharField(blank=True, max_length=400)),
                ('allergicHistory', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('body', models.CharField(max_length=10000)),
                ('artIMG', models.ImageField(default='artIMG/default.jpg', null=True, upload_to='artIMG/')),
                ('author', models.CharField(max_length=400)),
                ('datePosted', models.DateField()),
                ('approved', models.BooleanField()),
                ('numOfApprovals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('employeeID', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=1000)),
                ('firstName', models.CharField(max_length=400)),
                ('secondName', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('dob', models.DateField()),
                ('telphone', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=100)),
                ('profileIMG', models.ImageField(default='images/profileImages/default.jpg', null=True, upload_to='profileImages/')),
                ('documents', models.FileField(upload_to=medapp.models.custom_upload_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registryOwner', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=400)),
                ('datePosted', models.DateField()),
                ('body', models.CharField(max_length=1000)),
                ('stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DocReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medapp.review')),
                ('willRecomend', models.IntegerField()),
                ('doctor', models.CharField(max_length=100)),
            ],
            bases=('medapp.review',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('registereduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medapp.registereduser')),
                ('education', models.CharField(max_length=300)),
                ('aboutMe', models.CharField(max_length=500)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.DateField(null=True)),
                ('rating', models.IntegerField()),
                ('achievementStatus', models.IntegerField()),
                ('articlesApproved', models.ManyToManyField(to='medapp.Article')),
            ],
            bases=('medapp.registereduser',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('registereduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medapp.registereduser')),
                ('rating', models.IntegerField()),
                ('anamnesis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medapp.anamnesis')),
                ('favouriteDoctors', models.ManyToManyField(related_name='favouritesOnDoc', to='medapp.Doctor')),
                ('likedDoctors', models.ManyToManyField(related_name='likesOnDoc', to='medapp.Doctor')),
                ('registry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medapp.registry')),
            ],
            bases=('medapp.registereduser',),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateT', models.DateField()),
                ('specialization', models.CharField(max_length=400)),
                ('describtion', models.CharField(max_length=400)),
                ('methodology', models.CharField(max_length=400)),
                ('result', models.CharField(max_length=400)),
                ('documents', models.FileField(upload_to='illnessDocs/')),
                ('registry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medapp.registry')),
            ],
        ),
        migrations.CreateModel(
            name='likeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=400)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.article')),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateI', models.DateField()),
                ('specialization', models.CharField(max_length=400)),
                ('describtion', models.CharField(max_length=400)),
                ('diagnose', models.CharField(max_length=400)),
                ('active', models.BooleanField()),
                ('documents', models.FileField(upload_to='illnessDocs/')),
                ('registry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medapp.registry')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiryID', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=400)),
                ('body', models.CharField(max_length=400)),
                ('enquiryDate', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('moderator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='medapp.moderator')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.registereduser')),
            ],
        ),
        migrations.CreateModel(
            name='reviewDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewText', models.CharField(max_length=2000)),
                ('dateOfPublish', models.DateField(blank=True, default=datetime.datetime.now)),
                ('stars', models.IntegerField()),
                ('authorPatient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medapp.patient')),
                ('targetDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestDate', models.DateTimeField()),
                ('message', models.CharField(max_length=400)),
                ('documents', models.CharField(max_length=700)),
                ('status', models.CharField(max_length=200)),
                ('requestPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.patient')),
                ('targetDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultancyStartDate', models.DateTimeField(default=datetime.datetime.now)),
                ('consultancyEndDate', models.DateTimeField(default=datetime.datetime.now)),
                ('patientMessage', models.CharField(max_length=700, null=True)),
                ('doctorComments', models.CharField(max_length=700, null=True)),
                ('doctorConclusion', models.CharField(max_length=700, null=True)),
                ('status', models.CharField(max_length=700)),
                ('consultancyDoctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medapp.doctor')),
                ('consultancyPatient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ArtReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medapp.review')),
                ('authorType', models.CharField(max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.article')),
            ],
            bases=('medapp.review',),
        ),
    ]
