# Generated by Django 3.1.5 on 2021-04-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='status2',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
