# Generated by Django 3.1.5 on 2021-04-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0002_consultancy_status2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancy',
            name='status2',
        ),
    ]
