# Generated by Django 3.1.5 on 2021-04-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0003_remove_consultancy_status2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='consultancyEndDate',
            field=models.DateTimeField(),
        ),
    ]
