# Generated by Django 3.1.5 on 2021-04-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0004_auto_20210403_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='consultancyEndDate',
            field=models.DateTimeField(null=True),
        ),
    ]
