# Generated by Django 3.1.5 on 2021-04-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0006_auto_20210403_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='closeStatusDoctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='closeStatusPatient',
            field=models.BooleanField(default=False),
        ),
    ]
