# Generated by Django 3.1.5 on 2021-04-04 18:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0007_auto_20210403_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='articlesApproved',
        ),
        migrations.AddField(
            model_name='article',
            name='articlesApproved',
            field=models.ManyToManyField(related_name='approvalDoctor', to='medapp.Doctor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorDoctor', to='medapp.doctor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='datePosted',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
