# Generated by Django 3.1.5 on 2021-04-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0008_auto_20210404_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorsArticles', to='medapp.doctor'),
        ),
    ]
