# Generated by Django 3.1.5 on 2021-04-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0009_auto_20210404_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
