# Generated by Django 3.1.5 on 2021-04-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0010_article_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='articlesApproved',
        ),
        migrations.AddField(
            model_name='article',
            name='doctorsApprove',
            field=models.ManyToManyField(related_name='approvedArticles', to='medapp.Doctor'),
        ),
        migrations.AddField(
            model_name='article',
            name='doctorsDisapprove',
            field=models.ManyToManyField(related_name='disapprovedArticles', to='medapp.Doctor'),
        ),
    ]
