# Generated by Django 3.1.5 on 2021-04-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0012_article_numofdisapprovals'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='favouriteArticle',
            field=models.ManyToManyField(related_name='favouritesOnArticle', to='medapp.Article'),
        ),
        migrations.AddField(
            model_name='patient',
            name='likedArticle',
            field=models.ManyToManyField(related_name='likesOnArticle', to='medapp.Article'),
        ),
    ]
