# Generated by Django 3.1.5 on 2021-04-05 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0017_auto_20210405_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='profileIMG',
            field=models.ImageField(default='media/unlikeIcon.jpg', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='respondcomment',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 16, 32, 14, 620063)),
        ),
        migrations.AlterField(
            model_name='reviewarticle',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 16, 32, 14, 618962)),
        ),
    ]
