# Generated by Django 3.1.5 on 2021-04-05 18:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0019_auto_20210405_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondcomment',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 18, 37, 54, 15252)),
        ),
        migrations.AlterField(
            model_name='reviewarticle',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 18, 37, 54, 14769)),
        ),
        migrations.CreateModel(
            name='TreatmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='patientFiles/')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='IllnessFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileI', models.FileField(null=True, upload_to='patientFiles/')),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.illness')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultancyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='patientFiles/')),
                ('consultancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.consultancy')),
            ],
        ),
    ]
