# Generated by Django 3.1.5 on 2021-04-05 20:18

import datetime
from django.db import migrations, models
import medapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0020_auto_20210405_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancyfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='treatmentfile',
            name='file',
        ),
        migrations.AddField(
            model_name='consultancyfile',
            name='fileC',
            field=models.FileField(null=True, upload_to=medapp.models.consultancyFilesDirectory),
        ),
        migrations.AddField(
            model_name='treatmentfile',
            name='fileT',
            field=models.FileField(null=True, upload_to=medapp.models.treatmentFilesDirectory),
        ),
        migrations.AlterField(
            model_name='illnessfile',
            name='fileI',
            field=models.FileField(null=True, upload_to=medapp.models.illnessFilesDirectory),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='profileIMG',
            field=models.ImageField(default='media/unlikeIcon.jpg', null=True, upload_to=medapp.models.profileImageDirectory),
        ),
        migrations.AlterField(
            model_name='respondcomment',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 20, 18, 32, 930692)),
        ),
        migrations.AlterField(
            model_name='reviewarticle',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 20, 18, 32, 930194)),
        ),
    ]
