# Generated by Django 3.1.5 on 2021-04-05 23:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import medapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0021_auto_20210405_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondcomment',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 23, 0, 37, 732771)),
        ),
        migrations.AlterField(
            model_name='reviewarticle',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 23, 0, 37, 732272)),
        ),
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileR', models.FileField(null=True, upload_to=medapp.models.requestFilesDirectory)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.request')),
            ],
        ),
    ]
