# Generated by Django 3.1.5 on 2021-04-06 19:50

import datetime
from django.db import migrations, models
import medapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0026_auto_20210406_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phoneNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='work',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='profileIMG',
            field=models.ImageField(default='media/patientIcon.jpg', null=True, upload_to=medapp.models.profileImageDirectory),
        ),
        migrations.AlterField(
            model_name='respondcomment',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 19, 50, 29, 228113)),
        ),
        migrations.AlterField(
            model_name='reviewarticle',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 19, 50, 29, 227648)),
        ),
    ]
