# Generated by Django 3.1.5 on 2021-04-06 19:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import medapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0027_auto_20210406_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondcomment',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 19, 54, 11, 670788)),
        ),
        migrations.AlterField(
            model_name='reviewarticle',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 19, 54, 11, 670337)),
        ),
        migrations.CreateModel(
            name='DoctorFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileD', models.FileField(null=True, upload_to=medapp.models.doctorFilesDirectory)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.doctor')),
            ],
        ),
    ]
