# Generated by Django 3.1.5 on 2021-04-07 17:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0029_auto_20210406_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medapp.consultancy')),
            ],
        ),
        migrations.AlterField(
            model_name='respondcomment',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 7, 17, 40, 13, 986814)),
        ),
        migrations.AlterField(
            model_name='reviewarticle',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 7, 17, 40, 13, 986228)),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorType', models.CharField(max_length=1000)),
                ('messageText', models.CharField(max_length=1000)),
                ('datePosted', models.DateTimeField(default=datetime.datetime(2021, 4, 7, 17, 40, 13, 979874))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.registereduser')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.chat')),
            ],
        ),
    ]
