# Generated by Django 3.1.5 on 2021-04-07 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0031_auto_20210407_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='countMSG',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 20, 43, 33, 81028)),
        ),
        migrations.AlterField(
            model_name='respondcomment',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 7, 20, 43, 33, 97296)),
        ),
        migrations.AlterField(
            model_name='reviewarticle',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 7, 20, 43, 33, 96329)),
        ),
    ]
