# Generated by Django 3.1.5 on 2021-04-26 01:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medapp', '0033_auto_20210408_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancyfile',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 1, 2, 43, 937943)),
        ),
        migrations.AlterField(
            model_name='respondcomment',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 1, 2, 43, 946066)),
        ),
        migrations.AlterField(
            model_name='reviewarticle',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 1, 2, 43, 945542)),
        ),
    ]
